In [ ]:
# TensorFlow -> Deep Learning Framework 
# Tensors -> multidimensional matrices / anything with numeric values

In [ ]:
import tensorflow as tf
from tensorflow import keras

print("tensorflow version: " , tf.__version__)

tensorflow version:  2.12.0


In [ ]:
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train/255.0, X_test/255.0   # dividing by 255 to convert all values from 0-1 range

In [ ]:
# Build a Machine Learning Model
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])
X = tf.ones((3,3,))
X

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
predictions = model(X_train[:1]).numpy()
predictions

array([[ 0.43480793, -0.40070885, -0.05781052, -0.37890238, -0.5188954 ,
         0.62929666,  0.18560672,  0.00868893,  0.10379969,  0.11409636]],
      dtype=float32)

In [ ]:
# Convert these logits to probabilities for each class
tf.nn.softmax(predictions).numpy()

array([[0.14359191, 0.06226869, 0.08773816, 0.06364146, 0.05532761,
        0.17441964, 0.11191886, 0.09377107, 0.10312761, 0.10419497]],
      dtype=float32)

In [ ]:
# Define a loss function for training
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)
loss_fn

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

1.7462912

In [ ]:
# Before Training, compile the model
model.compile(optimizer = 'adam', loss= loss_fn, metrics = ['accuracy'])

In [ ]:
# Train and Evaluate the Model
model.fit(X_train, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0663 - accuracy: 0.9792
Epoch 2/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0580 - accuracy: 0.9816
Epoch 3/5
1875/1875 [==============================] - 10s 6ms/step - loss: 0.0526 - accuracy: 0.9830
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0473 - accuracy: 0.9846
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0446 - accuracy: 0.9849
313/313 - 1s - loss: 0.0733 - accuracy: 0.9802 - 672ms/epoch - 2ms/step


[0.07333255559206009, 0.9801999926567078]

In [ ]:
model.evaluate(X_test, y_test, verbose = 2)

313/313 - 1s - loss: 0.0733 - accuracy: 0.9802 - 501ms/epoch - 2ms/step


[0.07333255559206009, 0.9801999926567078]

In [ ]:
prob_model = tf.keras.Sequential(
    model, 
    tf.keras.layers.Softmax()
)

In [ ]:
prob_model.compile(optimizer = 'adam', loss= None, metrics= ['accuracy'])
prob_model.fit(X_train, y_train, epochs = 5)
prob_model.evaluate(X_test, y_test, verbose = 3)

Epoch 1/5


TypeError: ignored

In [ ]:
# Multi layer perceptrons -> neural networks containing multiple hidden layers
tf.compat.v1.disable_eager_execution()
tf.compat.v1.placeholder(dtype = tf.int32, shape = (28, 28), name = 'inputs')

<tf.Tensor 'inputs_2:0' shape=(28, 28) dtype=int32>

In [ ]:
# LOGITS
self.inputs()